// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using src.DeviceEmployeeAuthManager.DAL;

#nullable disable

namespace src.Migrations
{
    [DbContext(typeof(DeviceEmployeeDbContext))]
    [Migration("20250604012508_RenameTables")]
    partial class RenameTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Account");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmployeeId = 1,
                            Password = "hashedpassword1",
                            RoleId = 1,
                            Username = "admin.john"
                        },
                        new
                        {
                            Id = 2,
                            EmployeeId = 2,
                            Password = "hashedpassword2",
                            RoleId = 2,
                            Username = "jane.sys"
                        },
                        new
                        {
                            Id = 3,
                            EmployeeId = 3,
                            Password = "hashedpassword3",
                            RoleId = 2,
                            Username = "alice.pm"
                        },
                        new
                        {
                            Id = 4,
                            EmployeeId = 4,
                            Password = "hashedpassword4",
                            RoleId = 2,
                            Username = "bob.support"
                        },
                        new
                        {
                            Id = 5,
                            EmployeeId = 5,
                            Password = "hashedpassword5",
                            RoleId = 1,
                            Username = "eve.hr"
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeviceTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.ToTable("Device");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdditionalProperties = "{\"operationSystem\": null}",
                            DeviceTypeId = 1,
                            IsEnabled = false,
                            Name = "HP ProDesk 600 G6"
                        },
                        new
                        {
                            Id = 2,
                            AdditionalProperties = "{\"operationSystem\": \"Windows 11 Pro 23H2\"}",
                            DeviceTypeId = 1,
                            IsEnabled = true,
                            Name = "ThinkCentre M75q Gen 5 Tiny"
                        },
                        new
                        {
                            Id = 3,
                            AdditionalProperties = "{\"battery\": \"24%\"}",
                            DeviceTypeId = 2,
                            IsEnabled = true,
                            Name = "Apple Watch Ultra 2"
                        },
                        new
                        {
                            Id = 4,
                            AdditionalProperties = "{\"ipAddress\": \"192.168.0.1\", \"network\": \"example\"}",
                            DeviceTypeId = 3,
                            IsEnabled = false,
                            Name = "Raspberry Pi 4"
                        },
                        new
                        {
                            Id = 5,
                            AdditionalProperties = "{\"ports\": [{\"type\": \"HDMI\", \"version\": \"2.0\"}]}",
                            DeviceTypeId = 4,
                            IsEnabled = true,
                            Name = "Dell UltraSharp"
                        },
                        new
                        {
                            Id = 6,
                            AdditionalProperties = "{\"colors\": \"black and white\"}",
                            DeviceTypeId = 5,
                            IsEnabled = false,
                            Name = "HP LaserJet"
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.DeviceEmployee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DeviceEmployee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 1,
                            EmployeeId = 1,
                            IssueDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = 2,
                            EmployeeId = 2,
                            IssueDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 3,
                            EmployeeId = 3,
                            IssueDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = 4,
                            EmployeeId = 4,
                            IssueDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DeviceId = 5,
                            EmployeeId = 5,
                            IssueDate = new DateTime(2021, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DeviceType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Smartwatch"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Embedded"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Monitor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Printer"
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("PositionId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HireDate = new DateTime(2021, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonId = 1,
                            PositionId = 1,
                            Salary = 75000.00m
                        },
                        new
                        {
                            Id = 2,
                            HireDate = new DateTime(2022, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonId = 2,
                            PositionId = 2,
                            Salary = 65000.00m
                        },
                        new
                        {
                            Id = 3,
                            HireDate = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonId = 3,
                            PositionId = 3,
                            Salary = 90000.00m
                        },
                        new
                        {
                            Id = 4,
                            HireDate = new DateTime(2023, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonId = 4,
                            PositionId = 4,
                            Salary = 55000.00m
                        },
                        new
                        {
                            Id = 5,
                            HireDate = new DateTime(2019, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonId = 5,
                            PositionId = 5,
                            Salary = 80000.00m
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            MiddleName = "Michael",
                            PassportNumber = "AA123456",
                            PhoneNumber = "+1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PassportNumber = "BB654321",
                            PhoneNumber = "+1987654321"
                        },
                        new
                        {
                            Id = 3,
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            MiddleName = "Marie",
                            PassportNumber = "CC987654",
                            PhoneNumber = "+1123456789"
                        },
                        new
                        {
                            Id = 4,
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PassportNumber = "DD246810",
                            PhoneNumber = "+1222333444"
                        },
                        new
                        {
                            Id = 5,
                            Email = "eve.davis@example.com",
                            FirstName = "Eve",
                            LastName = "Davis",
                            MiddleName = "Grace",
                            PassportNumber = "EE135791",
                            PhoneNumber = "+1333555777"
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MinExpYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Position");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MinExpYears = 2,
                            Name = "Software Engineer"
                        },
                        new
                        {
                            Id = 2,
                            MinExpYears = 3,
                            Name = "System Administrator"
                        },
                        new
                        {
                            Id = 3,
                            MinExpYears = 5,
                            Name = "Project Manager"
                        },
                        new
                        {
                            Id = 4,
                            MinExpYears = 1,
                            Name = "IT Support"
                        },
                        new
                        {
                            Id = 5,
                            MinExpYears = 4,
                            Name = "HR Manager"
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Account", b =>
                {
                    b.HasOne("src.DeviceEmployeeAuthManager.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.DeviceEmployeeAuthManager.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Device", b =>
                {
                    b.HasOne("src.DeviceEmployeeAuthManager.Models.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId");

                    b.Navigation("DeviceType");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.DeviceEmployee", b =>
                {
                    b.HasOne("src.DeviceEmployeeAuthManager.Models.Device", "Device")
                        .WithMany("DeviceEmployees")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.DeviceEmployeeAuthManager.Models.Employee", "Employee")
                        .WithMany("DeviceEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Employee", b =>
                {
                    b.HasOne("src.DeviceEmployeeAuthManager.Models.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("src.DeviceEmployeeAuthManager.Models.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("src.DeviceEmployeeAuthManager.Models.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Device", b =>
                {
                    b.Navigation("DeviceEmployees");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Employee", b =>
                {
                    b.Navigation("DeviceEmployees");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Person", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("src.DeviceEmployeeAuthManager.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
